version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - 3001:3000
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - 5001:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge